Use ncdu 1.x
ncdu 2.x is written in zig [1]. Zig is not stable. It was recently
updated from 0.9.x to 0.10.x [2]. Some logic tried to keep 0.9.x on
macOS [3], but it did not work [4].

```
error: Package ‘zig-0.10.1’ in /nix/store/bqq0f9qwk3nn3icrzl5sfpmfbqb6yz95-nixpkgs/pkgs/development/compilers/zig/0.10.nix:59 is marked as broken, refusing to evaluate.
```

[1] https://dev.yorhel.nl/doc/ncdu2
[2] https://github.com/NixOS/nixpkgs/pull/210324
[3] https://github.com/NixOS/nixpkgs/commit/db76c9e04a75599c094d6ffccfcbf40c17004207
[4] https://github.com/NixOS/nixpkgs/issues/214545